src/http_template.cc
src/include/grpc_transcoding/http_template.h
test/http_template_test.cc
test/message_stream_test.cc

- Use unique_ptr in HttpTemplate::Parse
- remove unused namespace remapping

Various test fixes for Google import

---

src/include/grpc_transcoding/message_reader.h
src/include/grpc_transcoding/transcoder_input_stream.h
src/message_reader.cc
src/message_stream.cc
src/response_to_json_translator.cc
test/message_reader_test.cc
test/response_to_json_translator_test.cc

in ESP, gRPC client handles those errors, but pure HTTP/2 proxy (Envoy, NGINX HTTP/2 upstream) doesn't.

Add gRPC frame error handling

---

src/message_stream.cc
test/test_common.h

This is now consistent across all protobuf APIs.
It is no longer necessary to use the google::protobuf::int64 typedef.

Changed return of ByteCount() to use plain int64_t.

---

src/include/grpc_transcoding/path_matcher.h
test/path_matcher_test.cc

Only handle registered custom verbs and ignore any unknown ones.

Fix verb support

---

src/include/grpc_transcoding/path_matcher.h
test/path_matcher_test.cc

Implement underlying logic for `google.api.Http.fully_decode_reserved_expansion`.
Add a configurable option to always decode all path and query bindings.
Fixes #44

Support full decoding of reserved expansions

---

src/http_template.cc
src/include/grpc_transcoding/path_matcher.h
test/http_template_test.cc
test/path_matcher_test.cc

Signed-off-by: Wayne Zhang <qiwzhang@google.com>
To fix:  https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/issues/49
The root problem is:  current implementation is treating custom verb as last segment; replace ":" with "/".  It has limitation.
Changes: 
* treat custom verb as part of http_method; append custom verb to http_method for register and lookup, 
* not to append verb as last segment.
* variable.end_segment needs to be updated too.

Fix custom verb issue

---

.bazelrc

`.bazelrc` is copied from bazel rules_fuzzing: https://github.com/bazelbuild/rules_fuzzing/blob/f6062a88d83463e2900e47bc218547ba046dad44/.bazelrc
This gives us full OSS fuzz integration across multiple fuzzers.

Setup OSS Fuzz integration

---

src/include/grpc_transcoding/path_matcher.h
test/path_matcher_test.cc

Signed-off-by: Wayne Zhang <qiwzhang@google.com>
To fix https://github.com/envoyproxy/envoy/issues/13965
Changes:
* add a config bool query_param_unescape_plus to unescape + in query parameters
* rename unescape_spec to path_unescape_spec since it only applies to path.
* config grpc_transcoder filter config will expose this flag.

Support unescape plus in query parameters

---

src/BUILD
src/include/grpc_transcoding/type_helper.h
src/type_helper.cc

google::protobuf::type_info class is not thread safe as it is stated in the [code](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/internal/type_info.h#L49)
This change adds a mutex to protect it and to make TypeHelper class as thread safe

Make TypeHelper class thread safe

---

src/include/grpc_transcoding/message_reader.h
src/message_reader.cc
test/message_reader_test.cc

We will use this to optimize gRPC resource extraction in consumers of this library.

Expose parsed gRPC message size

---

src/include/grpc_transcoding/path_matcher.h
test/path_matcher_test.cc

Right now, the path matcher only match the registered custom verb. If it is unregistered and the trailing segment is wildcard, it will be part of that, causing a mismatch. For example,  `/foo/{x=*}` will matches `/foo/random:verb`, where `x` is bound to `random:verb`.
Add an option to always match the custom verb.

b/208716168: allow path matcher to always check custom verb

---

src/BUILD
src/include/grpc_transcoding/path_matcher.h
src/include/grpc_transcoding/percent_encoding.h
src/include/grpc_transcoding/type_helper.h
src/type_helper.cc
test/testdata/bookstore_service.pb.txt
test/type_helper_test.cc

To fix https://github.com/envoyproxy/envoy/issues/21151
In TypeHelper::ResolveFieldPath() which is used to lookup fields for query parameter binding.  If not found, and it is percent escaped,  try to un-escape it and lookup the name again.
Detail changes:
* Extract percent encoding code from "path_matcher.h" into a new file "percent_encoding.h" so it can be used by other path_matcher.h and type_helper.cc

Support percent escaped query parameters

---

README.md
script/check-style
src/include/grpc_transcoding/percent_encoding.h
src/include/grpc_transcoding/request_weaver.h
src/include/grpc_transcoding/status_error_listener.h
src/include/grpc_transcoding/type_helper.h
src/message_reader.cc
src/request_stream_translator.cc
src/request_weaver.cc
src/type_helper.cc
test/http_template_fuzz_test.cc
test/json_request_translator_test.cc
test/message_reader_fuzz_test.cc
test/message_reader_test.cc
test/path_matcher_test.cc
test/proto_stream_tester.cc
test/request_weaver_test.cc
test/response_to_json_translator_test.cc
test/status_error_listener_test.cc
test/type_helper_test.cc

Signed-off-by: Wayne Zhang <qiwzhang@google.com>
Notes:
* Original "http" doesn't work any more.  need to use "https"
* Keep using the old 3.8.0.  The latest clang-format versions pre-build binaries are in github, requires some redirection or permission, did not figure out how to download them in curl.

fix the script to format code

---

README.md
src/include/grpc_transcoding/response_to_json_translator.h
src/response_to_json_translator.cc
test/response_to_json_translator_test.cc

This PR is an implementation of newline-delimited JSON for streaming endpoints, as requested in #38. After this work is merged, it should be easier to implement JSON transcoding in a way that doesn't force consumers to wait for the end of a stream to collect messages as a single valid JSON array, allowing them to respond to each message individually.
Apologies in advance if I have committed any C++ sins, as it's been a while since I've used the language 🙏.

Add newline-delimited JSON response configuration

---

test/json_request_translator_test.cc
test/response_to_json_translator_test.cc
test/testdata/bookstore_service.pb.txt

The service config for Struct proto is incomplete as it's missing `map_entry` option in the `google.protobuf.Struct.FieldsEntry` type. This causes the protobuf parsing logic to run infinitely. The parser always assumes Struct has a map typed field, and it will [loop until it finds a map entry field](https://github.com/protocolbuffers/protobuf/blob/0264866ce665911787ba5ca0faf07a5efe2899dd/src/google/protobuf/util/internal/protostream_objectsource.cc#L516). When there's no `map_entry` field set, the field cannot be recognized as Map type, so the loop will go on forever by checking the same field again and again.
We just need to add in the `map_entry` option in the textproto.
Note the value field - the value is a bytes typed proto field, and it needs to contain the serialized value for …

Fix Struct proto service config in unit tests

---

WORKSPACE

When running `bazel test //test/...:all`, we'd see
```
ERROR: /usr/local/google/home/hongrux/.cache/bazel/_bazel_hongrux/c04ce887a8f743e196d4d0f4e5cc2f31/external/fuzzing_py_deps/pypi__absl_py/BUILD:5:11: no such package '@fuzzing_py_deps//pypi__enum34': BUILD file not found in directory 'pypi__enum34' of external repository @fuzzing_py_deps. Add a BUILD file to a directory to mark it as a package. and referenced by '@fuzzing_py_deps//pypi__absl_py:pypi__absl_py'
ERROR: Analysis of target '//test:message_reader_fuzz_test_corpus' failed; build aborted: Analysis failed
INFO: Elapsed time: 3.773s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (29 packages loaded, 1022 targets configured)
ERROR: Couldn't start the build. Unable to run tests
INFO: Build Event Protocol files …
```

Bump rules_fuzzing dependency to version 0.3.2

---

perf_benchmark/BUILD
perf_benchmark/benchmark.proto
perf_benchmark/benchmark_input_stream_translator_integration_test.cc
perf_benchmark/benchmark_main.cc
perf_benchmark/benchmark_service.textproto
perf_benchmark/utils.cc
perf_benchmark/utils.h

- Variable binding depth
- Number of variable bindings
This is a quick run with only one repetition of the benchmarks. Detailed results and analysis will be added to the README in a separate PR.
At a glance, having variable bindings would make the transcoding quicker. However, the benchmark doesn't account for the time to parse the bindings from the URI as we are just benchmarking for the transcoding process.
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                    Time             CPU   Iterations byte_latency byte_throughput message_latency message_throughput request_latency …
```

Add benchmarks for variable bindings

---

.bazelrc
WORKSPACE
perf_benchmark/BUILD
repositories.bzl
script/ci.sh

I'm not entirely sure if we want to merge this. Having this can be convenient for the community as it will be easier to reproduce our benchmark results by running it in a container.
Two new build targets added:
- Generate and run a docker container that has the benchmark binary
```
bazel run //perf_benchmark:benchmark_main_image
```
- Push the benchmark image to a container registry
```
bazel run //perf_benchmark:benchmark_main_image_push --define=PUSH_REGISTRY=gcr.io \
--define=PUSH_PROJECT=project-id \
--define=PUSH_TAG=latest
```

Add Bazel rules to package performance benchmark binary into a Docker image

---

perf_benchmark/benchmark_main.cc

`absl::StrAppend` is not suitable for appending large string, which will cause the benchmark script to crash.

Fix benchmark for gRPC streaming message builder logic to use std::stringstream

---

test/response_to_json_translator_test.cc

Signed-off-by: Wayne Zhang <qiwzhang@google.com>
Some compilers complain the `streaming_` variable is initialized out of order.

fix a init order issue in the test

---

.clang-format
.gitignore
Makefile
src/http_template.cc
src/include/grpc_transcoding/http_template.h
src/include/grpc_transcoding/internal/protobuf_types.h
src/include/grpc_transcoding/message_reader.h
src/include/grpc_transcoding/message_stream.h
src/include/grpc_transcoding/path_matcher.h
src/include/grpc_transcoding/percent_encoding.h
src/include/grpc_transcoding/request_message_translator.h
src/include/grpc_transcoding/request_weaver.h
src/include/grpc_transcoding/status_error_listener.h
src/include/grpc_transcoding/type_helper.h
src/message_reader.cc
src/request_stream_translator.cc
src/request_weaver.cc
src/response_to_json_translator.cc
src/status_error_listener.cc
src/type_helper.cc
test/path_matcher_test.cc

VariableBinding is a first class concept for path matcher and doesn't
need to be templated.
In addition, add a few developer tools.
* Clang format
* Makefile

    Remove unnecessary VariableBinding Templatization.

---

repositories.bzl

The new version has bazel support built-in, so we can drop the embedded BUILD file.

Update json library to 3.11.3

---

src/include/grpc_transcoding/response_to_json_translator.h
src/response_to_json_translator.cc
test/response_to_json_translator_test.cc

The response_to_json_translator currently supports streaming the messages as JSON array or as new line delimited. This PR adds support for enforcing Server-Sent Events (SSE) message framing (`data: <message>\n\n`) for streamed messages.

Add SSE style delimiting for message streaming

---

src/include/grpc_transcoding/response_to_json_translator.h
src/response_to_json_translator.cc
test/response_to_json_translator_test.cc

This PR 
- sets the default value for the introduced SSE params to avoid breaking the code for those not explicitly setting it.
- optimizes the SSE framing of the streamed response messages

Optimize the SSE delimiting of streamed messages
